spring:
  profiles:
    active: ${APP_ENV:dev}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none # или другое значение, например, validate
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://abb4ed5c33d2e2c2d3c3bc5290c593f3@o4506637797490688.ingest.sentry.io/4506637806993408
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
