spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:./h2/app
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: false
  liquibase:
    enabled: false
